### ISSUE TITLE
`as_<class>()` method to return self

### ISSUE THREAD

**Issue by joshwlambert** [socialcontactdata/contactmatrix#20]
Would it be beneficial to add a `as_contactmatrix()` S3 method for the `contactmatrix` class (`as_contactmatrix.contactmatrix()`)?

This is done in similar packages, e.g. {incidence2}: https://github.com/reconverse/incidence2/blob/main/R/as_incidence.R#L26-L30.

It could be of benefit for users using `as_contactmatrix()` in a pipeline where the class of the input object is not always known or if the user mistakenly thinks it is an object of another class to save them encountering an error: 

``` r
library(contactmatrix)
contactmat = new_contactmatrix(
  from  = c("[0,5)", "[5,10)",  "[5,10)"),
  to    = c("[0,5)", "[10,15)", "[15,20)"),
  value = c(0.32   , 0.46   , 0.72   )
)
as_contactmatrix(contactmat)
#> Error: `as_contactmatrix()` method not defined for this class of object
```

<sup>Created on 2024-11-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by Bisaloo** [comment]
Yes, this sounds good. Could you submit a PR for this please?
